# Generated by Django 4.2.6 on 2023-10-24 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('logo', models.ImageField(null=True, upload_to='Logos Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='titulo', max_length=50)),
                ('detalle', models.CharField(default='detalle', max_length=50)),
                ('visible', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_ultima_modificacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entidad')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_modificados', to=settings.AUTH_USER_MODEL)),
                ('publicado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_publicados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
