# Generated by Django 4.2.6 on 2023-10-24 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comunicado_tipo_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunicado',
            old_name='TIPO_CHOICES',
            new_name='tipo',
        ),
    ]
